### PR TITLE
Update to Go 1.14 and deploy app to Heroku dyno.

### PR DESCRIPTION
**Pull request by krashanoff**
This PR turned into a lot more than I anticipated. The gist is that this deploys our backend to a Heroku dyno and prepares it for the backend swap-out. Here's a breakdown of the changes:
* Switch our codebase to Go 1.14.
* Add a Heroku `Procfile`
* Add a `go.mod` file for our deps.
* Change the backend to use environment variables for credentials instead of a JSON file.
* Make our `Program`s use `string`s instead of `time.Time` to match the documents currently residing in the database.
* Remove deprecated or otherwise unused functions.
* Deny requests using unsupported methods from CORS.
* More intelligent, `mostRecentProgram`-aware program deletion in `db.HandleDeleteProgram`.
* Overhaul endpoint behavior for `db.HandleUpdateProgram`. We now use `uid` and `pid` query parameters to locate the document to update and verify it belongs to the user. Also, since the frontend only ever updates one document at a time, we can just treat the request body as a partial `Program` object.

### CODE REVIEW

**Comment by krashanoff** [comment]
Alright. This PR turned into a lot more than I anticipated. Here's all that I have done:

* Switch our codebase to Go 1.14.
* Add a Heroku `Procfile`
* Add a `go.mod` file for our deps.
* Change the backend to use environment variables for credentials instead of a JSON file.
* Make our `Program`s use `string`s instead of `time.Time` to match the documents currently residing in the database.
* Remove deprecated or otherwise unused functions.
* Deny requests using unsupported methods from CORS.
* More intelligent, `mostRecentProgram`-aware program deletion in `db.HandleDeleteProgram`.
* Overhaul endpoint behavior for `db.HandleUpdateProgram`. We now use `uid` and `pid` query parameters to locate the document to update and verify it belongs to the user. Also, since the frontend only ever updates one document at a time, we can just treat the request body as a partial `Program` object.

Things are looking in pretty good shape. Sorry for dumping so much information on you all so suddenly. Hope that you're all in good health and had a good finals week. Here's to the start of spring break!

**Comment by malsf21** [comment]
Can you do me a quick favour and update the PR title + description with your comments? I think we'll start auto-generating changelogs soon and that would be helpful. Super excited to see all of this happen 😄

**Comment by krashanoff** [comment]
@malsf21 You got it chief :+1:

**Comment by krashanoff** [comment]
Superceded by #10

**Pull request closed without merging**
