### PR TITLE
Lift db#DB.GetUser from its associated type via Echo handler association. Introduce database mocking system.

### PR DESCRIPTION
**Pull request by krashanoff**
## Summary

Took a while to get to this pull request, but here it is. This pull request is intended to be the first of many in refactoring our backend's monolithic DB type into something more general - a Go interface. The advantages of such a shift should be immediately apparent, granting the backend greater control over its database operations, easier testing possibilities, and a wider range of freedom in its choice of backend. For example, with our database operations abstracted behind an interface, we can now write a mock database type for offline testing and use.

Secondary to the freedom afforded, these changes will decouple our handler functions from a single data type, and make testing not only easier but **consistent**, lending our codebase to a more logical organization. This will make it easier for future members to modify the backend and continue its development beyond our tenure.

## Features

This pull request makes the following modifications:
- Adds an interface `db#TLADB` describing the basic operations a Teach LA backend must perform.
- Adds a type, `db#DBContext`, extending `echo#Context` with a member satisfying the `db#TLADB` interface.
- Adds basic functionality enabling `db#DB` to satisfy the aforementioned interface.
- Adds a new type `db#MockDB` implementing `db#TLADB` completely offline for testing purposes.
- Adds custom middleware to `server.go` enabling this custom context in all requests.
- Removes the `DB#GetUser` function from the associated `DB` type into its own package, `handlers`.
- Adds basic tests to the `handlers` package for the new endpoint using the mock type.

## Concerns, Prerequisites to Merging

This pull request is a step in the right direction, but there are some issues I think I'd like to handle before moving forward with it:
- [ ] ~~Add lightweight locking to data types to give the backend itself control over how transactions are executed, and the desired degree of consistency.~~
- [x] Add more detailed tests to the new handler function.
- [x] Add verbose logging to the handler function.

## Future Changes

I will put the following in a separate issue, but going forward, if anyone would like to help in this refactor, the steps are as follows:
1. Extend the interface as you see fit for the functionality you must implement.
2. Implement said extensions on the `MockDB` and `DB` types.
3. Write a handler function in the `handler` package, mirroring the patterns used in this PR's `GetUser` function.
4. Write basic tests for the new endpoint using the `MockDB` type.

### CODE REVIEW

**Comment by krashanoff** [comment]
I have tagged @jonathanbcarlson for review as they expressed interest in this refactor.

**Comment by krashanoff** [comment]
I'll just decouple the concurrency concerns from this PR for the moment as they seem outside its scope. Ready for review.

**Comment by krashanoff** [comment]
image

Regarding this, I don't really know why the lint is failing. I don't believe I pass a `nil` Context anywhere in my changes.

**Comment by lumisphere902** [comment]
> Regarding this, I don't really know why the lint is failing. I don't believe I pass a `nil` Context anywhere in my changes.

I believe you are passing a nil context to StoreClass

**Review by lumisphere902 — APPROVED** [review]
LGTM. Just have 1 concern; does this mean that any new database function would also have to be separately implemented for the MockDB? It shouldn't be a ton of extra work, but it seems like something that could get easily forgotten.

**Comment by krashanoff** [comment]
> Does this mean that any new database function would also have to be separately implemented for the MockDB?

With my current solution, yes. It is definitely a trivial but bothersome amount of work for people modifying the `TLADB` interface, but my thinking is that when the interface is finalized, future modifications will only be adding on. In exchange, we get offline testing and operation, which is a significant advantage against our current online-only solution. For example, developers could run a fresh copy of our database completely in memory.

**Comment by krashanoff** [comment]
I'll likely be modifying the interface before merging so that on save, the `TLADB` returns the updated struct. This is useful for instances where the database interface may want to mutate the object before saving.

**Comment by jonathanbcarlson** [comment]
LGTM, I'm excited for better and easier testing!

**Review by jonathanbcarlson — APPROVED** [review]
LGTM, I'm excited for better and easier testing!

**Comment by krashanoff** [comment]
Will make future changes to `TLADB` in another issue. I won't tack on more work to this PR for fear of killing progress. For now, I have moved the `MockDB` to its own file to prevent polluting of `db.go`. All set; going to go ahead and merge.

**Pull request merged**
