### PR TITLE
[DRAFT] Implementing the class feature and human friendly 3-word hash

### PR DESCRIPTION
**Pull request by tfukaza**
Requesting review of a draft which implements the following features:
- Class struct (in `class.go`)
- Handlers for requests related to classes (`classManagement.go`)
- Additional functions in `db.go` to communicate class-related  information with Firebase 
- Generation of a 3-word hash (`tools/tinycrypt`) for a given pid/cid, which will be stored in Firebase.

Some notes:
- In `tinycrypt`, the only function used is `GenerateWord36()` Other functions are not used, but are kept as it _might_ be needed in the future in case hash collision becomes a problem, although it is unlikely since we have 68 billion slots.
-  ~~`MakeAlias()` in `db.go` has a known bug, where the 36 bit hash is used to check if a hash is already taken, when it is supposed to use the 3-word hash (since the document keys stored in Firebase use the 3-word hash)~~ Has been fixed.

### CODE REVIEW

**Comment by malsf21** [comment]
Just a quick thing from me - should we be committing the entire words dictionary into git? Is there some way that we could install it package-wise instead, since it'll bloat up our version control?

**Comment by tfukaza** [comment]
Yeah I agree that 5k + line package looks awful, I'll discuss with @krashanoff what we can do

**Comment by malsf21** [comment]
Quick reminder - we should squash merge this (we don't need the word file in the repo history haha). Great work @tfukaza!

**Comment by krashanoff** [comment]
Hey Tomo! Sorry for letting this hang for so long! I'm going to review this a little later today to get it merged before we make the changes updating our codebase to 1.14.

**Pull request closed without merging**
